### ISSUE TITLE
Pass a variable as separator

### ISSUE THREAD

**Issue by arfeo** [ben-strasser/fast-cpp-csv-parser#62]
Is there any way to pass a `char` variable as a separator? Thanks.

**Comment by dallaires** [comment]
Since the separator is pass over a template, the value must be known at compile time. You may pass a `char` if it is a `constexpr`. One way to work around would be to use a factory or an abstract factory that return the desired parser with the correct separator.

**Comment by ben-strasser** [comment]
There is no way in the provided interface. The reason is that it seems like a very awkward requirement to me to specify the separator at runtime and thus the code was not written with this scenario in mind. Changing it in the code is also not so easy. The separator is part of the quote_policy. So I am afraid that the answer is a simple "no". Sorry.
