### ISSUE TITLE
need support for CR as the line delimiter

### ISSUE THREAD

**Issue by stevenklassen8376** [ben-strasser/fast-cpp-csv-parser#64]
I'm not sure where these files came from (this was the standard for Mac OS9 but I know they are not that old). But I have to be able to deal with them.

**Comment by stevenklassen8376** [comment]
I have a fix ready to push if you want to grant me permission.

**Comment by ben-strasser** [comment]
Hi,

thanks for the patch.

Newline endings are very tricky. Consider the case when someone in Linux writes the string "foo\rbar" to a file. If he reads it back in, he does not expect to have generated a line end. 

There are already problems of this sort because mixing Windows and Unix newlines is allowed. However, currently I believe that the corner cases are rare enough to be acceptable. I do not think that this trade-off is true for old Apple newlines.

I think the easiest way to deal with such files is piping them trough "tr '\r' '\n'" in the shell.

Best Regards
Ben Strasser

**Comment by stevenklassen8376** [comment]
Your response isn't quite clear to me. Would you like me to push the patch or not?

As for where my files came from, it turns out them come from some firmware beyond our control. It's not that old so I'm surprised by their developers' choice, but I have to deal with it nonetheless.

**Comment by ben-strasser** [comment]
I do not want to add the patch to the mainline and gave a reason as to why.

If I was in your situation, I would pipe the output of the firmware through "tr '\r' '\n'" and be done with it.

Best Regards
Ben Strasser

**Comment by stevenklassen8376** [comment]
Ok, thanks. I don't like the extra piping but I'll keep my patch local. An alternative that I may consider is to assume the newline is "\n" but allow it to be changed in the constructor or something.

But for now you can consider this issue as closed.
