### ISSUE TITLE
Improvement: handle a string where a number is expected

### ISSUE THREAD

**Issue by ccocheci** [ben-strasser/fast-cpp-csv-parser#65]
Right now the parser cannot handle something like "nan" where an integer or double is expected. It would be nice to be able to pass a flag telling the parser to do something other than throw on exception in this case.

**Comment by ccocheci** [comment]
Hi Ben,
It could be the default value for the type (0), or the max value for the type, depending on the flag value.
Thank you,
Cristian Cocheci

**Comment by ben-strasser** [comment]
Hi,

just so that I understand you correctly: You suggest that, if someone writes the value of sqrt(-1.0) to a file and then reads it back in as int the obtained value should be silently 0? That sounds like a recipe for disaster. If this really is the behavior that you want, I highly recommend making it explicit in your code and read the field as char* and use atof combined with an if-then-else.

What I actually was referring to, was that there is not just one nan value. A 32-bit IEEE floating point has 16777215 nan states. Which one should the string "nan" decode to? IEEE floating points nans contain an error that encodes the reason why something is nan. For example, 1/0.0 has a different bit pattern than sqrt(-1.0).

Best Regards
Ben Strasser

**Comment by ben-strasser** [comment]
Why not use

char*str_val;
while(read_row(str_val)){
   double val;
   if(strcmp(str_val, "nan"))
     val = atof(str_val);
   else
     val = 42;
}

I do not think that you can make the code any clearer than that. The 
buildin decoder is also not really faster than that because the char* 
goes directly into the file buffer.

Best Regards
Ben Strasser

**Comment by ccocheci** [comment]
Sure, I can do this, of course. Indeed nan is too particular of a case, no reason to include it in the general options.
Thank you.
Cristian
