### ISSUE TITLE
linefeeds in quoted values

### ISSUE THREAD

**Issue by petehug** [ben-strasser/fast-cpp-csv-parser#69]
Consider this csv file:
`col1,col2,col3,col4`
`1,1,"a",0`
`1,2,"a`
`b",0`

The second row after the header has a quoted value with a cr/lf. This throws a error::escaped_string_not_closed() exception.

**Comment by ben-strasser** [comment]
Hi,

thanks for the report.

Can you please provide a minimum C++ file that demonstrates the problem?

Best Regards
Dr. Ben Strasser

**Comment by petehug** [comment]
BTW, here is how the Notepad++ plugin CSV Query shows the parsed output from the test file. (Note that CSV Query is based on SQLite. Although row 2 column 3 shows as 'ab', if I change the query string to SELECT *, HEX(col3) FROM THIS I'm getting 610D0A62 for 'ab' which is what I would expect).

![test](https://user-images.githubusercontent.com/653226/43105216-37dd1d9a-8f28-11e8-8af3-692bd78724f9.png)

**Comment by petehug** [comment]
BTW, here is how the Notepad++ plugin CSV Query shows the parsed output from the test file (the last column shows you the value of col3 in hex and demonstrates that the cr/lf is correctly preserved between the a and b of 'ab').

![test](https://user-images.githubusercontent.com/653226/43105896-a9bcf578-8f2a-11e8-8338-2b62a9f9e7cc.png)

**Comment by petehug** [comment]
Hi Ben,

I made some changes to csv.h to address this issue (see below).

I haven't tried, but I'm almost certain that reporting of parse errors may report invalid line number reference if the error occurs after a row with line breaks in one or more values.

Thanks,
Pete
 
[csv.h.txt](https://github.com/ben-strasser/fast-cpp-csv-parser/files/2275967/csv.h.txt)

**Comment by ben-strasser** [comment]
Sorry for the late response. From your first post it was unclear to me what you wanted to achieve. Now I understand but sorry: wont implement. 

Newlines within quotes have been requested many times in the past and it's a feature that will now be implemented. For a detailed reasoning, please look at the exiting issues. The summary is:

* Mixing Linux and Windows Newlines within one file is allowed. As a result it is ambiguous how a column with the content "a\r\nb" should parsed. Is the \r part of the newline or part of the string? I.e., should this decode as "a\r\nb" or as "a\nb"?
* Because of the way the interfaces are setup, major breaking changes would be necessary to support some form of this.

Best Regards
Ben Strasser

**Comment by BeanCounterMacc** [comment]
Hi Ben,

Thanks for this parser github project. It is a time saver...unless there are CRs or NLs in quotes. For now, I'm replacing them within Excel before I save the CSV file; however, this is becoming taxing.

Could this issue, of CRs and NLs within quotes, be tackled by determining how many delimiters(columns) the CSV file has inherently? With this assumption of the data's symmetrical structure, it would be a matter of comparing the quantity of delimiters(columns) in each "in.read_row" buffer to the CSV's delimiter(column) count.

For example, If the buffer is less than the CSV's delimiter(column) count, then the code could concatenate subsequent CR/NLs, until the buffer is >= to the CSV's number of delimiters. Then, finally, either throw the error that buffer's delimiter(column) count is > CSV's count or, continue if they are equal.

I apologize for not making a pull request. I'm a novice programmer and would only make a mess of the project file...

Thanks,
B.C.M
